Repository surfstudio/yandex-mapkit-lite-flutter, pull requests merged in 2024-02, with the labels that each got.

#5 feat: Add skip testing
  .github/workflows/publish_to_pub.yml
Labels: enhancement

#6 fix: Removed testing from needs
  .github/workflows/publish_to_pub.yml
Labels: bug

#7 fix(no-task): fixed lite dependencies for iOS and Android
  CHANGELOG.md
  README.md
  android/build.gradle
  android/src/main/java/com/unact/yandexmapkit/Utils.java
  android/src/main/java/com/unact/yandexmapkit/YandexMapkitPlugin.java
  example/README.md
  example/android/app/build.gradle
  ios/Classes/Utils.swift
  ios/yandex_mapkit_lite.podspec
  pubspec.yaml
Labels: bug

#13 docs: Add more presentable README
  .markdownlint.json
  README.md
  assets/yandex_mapkit_lite.dark.png
  assets/yandex_mapkit_lite.light.png
Labels: documentation

#17 fix: github-action-json-file-properties after update version
  .github/workflows/main.yml
  .github/workflows/publish_to_pub.yml
Labels: bug
